// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DateRange struct {
	Start string `json:"start"`
	End   string `json:"end"`
}

type Deployment struct {
	ID               string `json:"ID"`
	DeploymentID     int    `json:"deploymentID"`
	Status           string `json:"status"`
	EnvironmentName  string `json:"environmentName"`
	ProjectID        int    `json:"projectID"`
	ProjectName      string `json:"projectName"`
	ProjectGroupName string `json:"projectGroupName"`
	FinishedAt       string `json:"finishedAt"`
	Duration         int    `json:"duration"`
}

type Project struct {
	ID        string `json:"ID"`
	ProjectID string `json:"projectID"`
	Name      string `json:"name"`
	GroupName string `json:"groupName"`
}
